### ISSUE TITLE
Conversion of Test Run EVIO to LCIO is broken

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#184]
I get the following error:

```
org.hps.record.svt.SvtEvioExceptions$SvtEvioHeaderException: ROC 1 multisample count 96 is not consistent with bank size 0
        at org.hps.evio.AbstractSvtEvioReader.checkSvtSampleCount(AbstractSvtEvioReader.java:300)
        at org.hps.evio.AbstractSvtEvioReader.makeHits(AbstractSvtEvioReader.java:197)
        at org.hps.evio.LCSimTestRunEventBuilder.makeLCSimEvent(LCSimTestRunEventBuilder.java:103)
        at org.hps.evio.EvioToLcio.run(EvioToLcio.java:618)
        at org.hps.evio.EvioToLcio.main(EvioToLcio.java:98)
        at org.hps.test.it.ConditionsIT.testEvioToLcioTestRun(ConditionsIT.java:54)
```

The crash can be fixed by adding the following method to `TestRunSvtEvioReader` to override the super class method:

```
protected void checkSvtSampleCount(int sampleCount, SvtHeaderDataInfo headerData) throws SvtEvioHeaderException { 
}
```

Then I get output, though I have no idea if it is converting correctly or not.

**Comment by omar-moreno** [comment]
@JeremyMcCormick what file are you using to check the conversion is correct?  The EVIO structure changed a few times during the test run so we should make sure you are using a valid file.
