### ISSUE TITLE
Resolve "dPhi large Exception"

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#245]

**Comment by normangraf** [comment]
I have skimmed off some events from run 5796 that exhibit the "dPhi too large" excpetion. The file can be found online at:

http://www.lcsim.org/test/hps-java/problemFiles/dPhiException_5796_events.evio

Run with the command:

java -cp ~/git/hps-java/distribution/target/hps-distribution-4.0-SNAPSHOT-bin.jar  org.hps.evio.EvioToLcio -r -x /org/hps/steering/recon/EngineeringRun2015FullRecon.lcsim -d HPS-EngRun2015-Nominal-v6-0-fieldmap -D outputFile=tstdPhi dPhiException_5796_events.evio -e 1

This will throw the exception on event 50411706, viz.

[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411656; time: 1431932340831844372; seq: 0
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50391404; time: 1431932339757683372; seq: 1
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411719; time: 1431932340835394464; seq: 2
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411731; time: 1431932340836118308; seq: 3
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411744; time: 1431932340836851960; seq: 4
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411770; time: 1431932340838255556; seq: 5
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411796; time: 1431932340839704240; seq: 6
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411889; time: 1431932340844637084; seq: 7
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411919; time: 1431932340846009332; seq: 8
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411950; time: 1431932340847356240; seq: 9
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411966; time: 1431932340848011220; seq: 10
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411978; time: 1431932340848644884; seq: 11
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50412021; time: 1431932340850731148; seq: 12
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50412034; time: 1431932340851442996; seq: 13
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50412060; time: 1431932340852859704; seq: 14
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411706; time: 1431932340834661376; seq: 15
Exception in thread "main" java.lang.RuntimeException: dphi is large 5.285079693768026 from phi0 -2.741160997740266 and phinew 2.5439186960277604 take care of the ambiguity!!??
        at org.hps.recon.tracking.TrackUtils.getParametersAtNewRefPoint(TrackUtils.java:207)
        at org.hps.recon.tracking.TrackUtils.getParametersAtNewRefPoint(TrackUtils.java:171)
        at org.hps.recon.tracking.gbl.FittedGblTrajectory.getCorrectedPerigeeParameters(FittedGblTrajectory.java:287)
        at org.hps.recon.tracking.gbl.FittedGblTrajectory.getCorrectedPerigeeParameters(FittedGblTrajectory.java:235)
        at org.hps.recon.tracking.gbl.MakeGblTracks.makeCorrectedTrack(MakeGblTracks.java:101)
        at org.hps.recon.tracking.gbl.MakeGblTracks.makeCorrectedTrack(MakeGblTracks.java:66)
        at org.hps.recon.tracking.gbl.MakeGblTracks.refitTrack(MakeGblTracks.java:179)
        at org.hps.recon.tracking.gbl.GBLRefitterDriver.process(GBLRefitterDriver.java:81)
        at org.lcsim.util.Driver.doProcess(Driver.java:261)
        at org.lcsim.util.Driver.processChildren(Driver.java:271)
        at org.lcsim.util.Driver.process(Driver.java:187)
        at org.lcsim.util.DriverAdapter.recordSupplied(DriverAdapter.java:74)
        at org.lcsim.job.JobControlManager.processEvent(JobControlManager.java:819)
        at org.hps.evio.EvioToLcio.run(EvioToLcio.java:618)
        at org.hps.evio.EvioToLcio.main(EvioToLcio.java:92)

This, too, is non-deterministic. Skipping different numbers of events before encountering this particular event may or may not result in this Exception being thrown.

**Comment by sebouh137** [comment]
I believe I have fixed this problem today using branch issue245. What I do here (in TrackUtils, lines 191-194) is that if |phi0| > pi/2, then I add (subtract) pi to phi0 in order to ensure that |phi0| < pi/2.  This no longer kills the JVM for the event that Norman specified (regardless of how many events are skipped beforehand).  While the track refitting does eventually abort for that track ("Can't find track intercept; aborting Track refit"), the event processing continues as usual after that without shutting down the JVM:

...
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50412060; time: 1431932340852859704; seq: 14
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50411706; time: 1431932340834661376; seq: 15
WTrack: this track started to go backwards?! params [WTrack params [NaN, NaN, NaN, 0.010750132852998213, NaN, NaN, NaN, ]
 with corresponding HelicalTrackFit:
HelicalTrackFit: 
d0= -223.9683378238775
phi0= -1.2490855046401235
curvature: 0.006701131315600917
z0= 5.605964738748672
tanLambda= 0.04911199930600597
]
Can't find track intercept; aborting Track refit
[INFO] [org.lcsim.job.EventPrintLoopAdapter] event: 50412165; time: 1431932340858227232; seq: 16
[INFO] [org.hps.evio] Last physics event time: 1431932340 - Mon May 18 02:59:00 EDT 2015
EventFlagFilter Summary: 
events processed = 17
events passed    = 12
       rejection = 0.7058823529411765
[INFO] [org.hps.evio] Job finished successfully!

**Comment by normangraf** [comment]
Resolved with PR #246
