### ISSUE TITLE
Fix broken conditions command line tool

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#259]
Needs database conditions manager setup.

```
INFO: Setting up the conditions manager ...
java.lang.ClassCastException: Cannot cast org.lcsim.conditions.ConditionsManagerImplementation to org.hps.conditions.database.DatabaseConditionsManager
	at java.lang.Class.cast(Class.java:3369)
	at org.hps.conditions.database.DatabaseConditionsManager.getInstance(DatabaseConditionsManager.java:80)
	at org.hps.conditions.cli.CommandLineTool.setupConditionsManager(CommandLineTool.java:178)
	at org.hps.conditions.cli.CommandLineTool.run(CommandLineTool.java:144)
	at org.hps.conditions.cli.CommandLineTool.main(CommandLineTool.java:66)
```

**Comment by JeremyMcCormick** [comment]
Resolved by #260.
