### ISSUE TITLE
Old reconstruction release crashes

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#289]
In trying to reproduce some interesting differences in track reconstruction efficiencies over time pointed out by Alessandra this morning, I downloaded some earlier production jar files from nexus and tried to run the reconstruction. I encountered the following error when running the 3.9 jar file:

```
java -cp hps-distribution-3.9-bin.jar org.hps.evio.EvioToLcio -x EngineeringRun2015FullRecon.lcsim -d HPS-EngRun2015-Nominal-v5-0-fieldmap -D outputFile=tst hps_005772.evio.0 
```

```
2018-01-22 13:05:58 [CONFIG] org.hps.conditions.database.DatabaseConditionsManager initialize :: initializing with detector HPS-EngRun2015-Nominal-v5-0-fieldmap and run 5772
2018-01-22 13:05:58 [CONFIG] org.hps.conditions.database.DatabaseConditionsManager setXmlConfig :: setting XML config from resource /org/hps/conditions/config/conditions_database_engrun.xml
2018-01-22 13:05:58 [CONFIG] org.hps.conditions.database.DatabaseConditionsManager loadConfiguration :: setupSvtDetector = true
2018-01-22 13:05:58 [CONFIG] org.hps.conditions.database.DatabaseConditionsManager loadConfiguration :: freezeAfterInitialize = false
2018-01-22 13:05:58 [CONFIG] org.hps.conditions.database.DatabaseConditionsManager registerConverters :: registering default conditions converters
2018-01-22 13:05:58 [INFO] org.hps.conditions.database.DatabaseConditionsManager openConnection :: opening connection ...
connection: jdbc:mysql://hpsdb.jlab.org:3306/
host: hpsdb.jlab.org
port: 3306
user: hpsuser
database: hps_conditions
Exception in thread "main" java.lang.RuntimeException: Error initializing conditions system.
        at org.hps.evio.EvioToLcio.checkConditions(EvioToLcio.java:235)
        at org.hps.evio.EvioToLcio.bufferEvents(EvioToLcio.java:205)
        at org.hps.evio.EvioToLcio.run(EvioToLcio.java:501)
        at org.hps.evio.EvioToLcio.main(EvioToLcio.java:98)
Caused by: org.lcsim.conditions.ConditionsManager$ConditionsNotFoundException: Conditions not found for detector HPS-EngRun2015-Nominal-v5-0-fieldmap
        at org.lcsim.conditions.ConditionsReader.create(ConditionsReader.java:197)
        at org.lcsim.conditions.ConditionsReader.create(ConditionsReader.java:214)
        at org.lcsim.conditions.ConditionsManagerImplementation.setDetector(ConditionsManagerImplementation.java:40)
        at org.hps.conditions.database.DatabaseConditionsManager.initialize(DatabaseConditionsManager.java:714)
        at org.hps.conditions.database.DatabaseConditionsManager.setDetector(DatabaseConditionsManager.java:1021)
        at org.hps.evio.EvioToLcio.checkConditions(EvioToLcio.java:233)
        ... 3 more
```

Running the same command using the hps-distribution-4.0-bin.jar file (also fetched from nexus) runs to completion.

Any suggestions on what I might have done wrong or forgotten to do would be appreciated.

**Comment by JeremyMcCormick** [comment]
The detector does not exist in this release of hps-java.

Suggested remedy is pulling in the detector files from the master and rebuilding your distribution:

```
cd hps-java
git checkout hps-modules-3.9
git checkout master -- detector-data/detectors/HPS-EngRun2015-Nominal-v5-0-fieldmap
mvn clean install
```

This is a side effect of only using the jar for packaging detector files.  You cannot automatically use a new detector on an older release where the detector didn't exist without checking out the detector files and rebuilding.
