### ISSUE TITLE
Calorimeter Truth Time and Metadata Error

### ISSUE THREAD

**Issue by mccaky** [JeffersonLab/hps-java#298]
Calorimeter truth data needs to output all of the SLIC truth hits that went into the ADC buffers that are written upon a trigger into the output file. By default, the hit times are defined as a displacement from the start of the beam bunch time in which they occurred. They need to be defined in terms of time displacement from the start of the readout window instead. Thus, a copy is created and written out that is identical, but with a modified time. The `LCMetaData` and time values do not correctly write, however. `LCMetaData` is found to be null and the time is always zero.

This process is performed in the class `org.hps.readout.ecal.updated.EcalReadoutDriver` in the `hps-ecal-readout-sim` package in the method `getTriggerTruthValues(long, double)`.

The `CalorimeterHit` objects are generated using the method:

`new BaseCalorimeterHit(hit.getRawEnergy(), hit.getCorrectedEnergy(), hit.getEnergyError(), baseHitTime + hit.getTime(), hit.getCellID(), hit.getPositionVec(), hit.getType(), hit.getMetaData())`

Here, `hit` is the existing `CalorimeterHit` object that is to be cloned.

It is observed that the hits are correctly generated and output to the readout file, but do not contain all the data, as specified above.

This may be a consequence of the LCIO readout flags. These are defined in the method `startOfData()` in the lines:

```
// Define the LCSim collections for the truth data.
truthHitsCollectionParams = new LcsimCollection<CalorimeterHit>("EcalTruthHits", this, CalorimeterHit.class, 0.0);
truthHitsCollectionParams.setFlags(0xe0000000);
truthRelationsCollectionParams = new LcsimCollection<LCRelation>("EcalTruthRelations", this, LCRelation.class, 0.0);
```

Note that the output hit collection is "EcalTruthHits".

[Edit] - Process can be run with the command from the iss166 branch:

`java -DdisableSvtAlignmentConstants=true -jar $HPS_JAVA_166 ReadoutManagerTest_NoDebug.txt -i [INPUT] -Drun=7986 -Ddetector=HPS-PhysicsRun2016-Nominal-v5-0-fieldmap -DoutputFile=[OUTPUT] -n 1000`

I use the input file `/work/hallb/hps/mccaky/slic_2pt3_34.slcio` for testing.

[ReadoutManagerTest_NoDebug.txt](https://github.com/JeffersonLab/hps-java/files/1712796/ReadoutManagerTest_NoDebug.txt)

**Comment by mccaky** [comment]
I updated the code some -- `CalorimeterHit` objects can now be properly cloned to retain truth information if they are actually `SimCalorimeterHit` objects. All cloning was copied to a method called `cloneHitToTime(CalorimeterHit, double)`, which handles both the specific case of the `SimCalorimeterHit` and the more general case of generic `CalorimeterHit`. The time and metadata issues both remain, though.

Another issue that is worth examining is that cluster objects written into the output LCIO data always list their number of hits as 1 regardless of the actual number of hits the cluster had. Clusters are generated in the `ecal-readout-sim` package class `org.hps.readout.ecal.updated.GTPClusterReadoutDriver`.

I suspect that this issue is either a problem with the LCIO flags, or possibly because the hits which make up a cluster are not actually included in the output file. This issue can be observed by running the same command as mentioned above.

[Edit] - Also note that tabs have finally been removed from issue code.

**Comment by mccaky** [comment]
Attempted to add a second cluster collection to the output that also includes all of the hits associated with the clusters to see if this fixed the issue, but an error is now occurring when these particular hits are output.

```
java.lang.NullPointerException
        at org.lcsim.event.base.BaseHit.findDetectorElement(BaseHit.java:219)
        at org.lcsim.event.base.BaseHit.calculatePosition(BaseHit.java:189)
        at org.lcsim.event.base.BaseHit.getPosition(BaseHit.java:166)
        at org.lcsim.lcio.SIOCalorimeterHit.write(SIOCalorimeterHit.java:74)
        at org.lcsim.lcio.SIOCalorimeterHitBlockHandler.writeCollectionElement(SIOCalorimeterHitBlockHandler.java:40)
        at org.lcsim.lcio.AbstractBlockHandler.writeBlock(AbstractBlockHandler.java:55)
        at org.lcsim.lcio.LCIOWriter.writeData(LCIOWriter.java:220)
        at org.lcsim.lcio.LCIOWriter.write(LCIOWriter.java:254)
        at org.hps.readout.ReadoutDataManager.process(ReadoutDataManager.java:210)
        at org.lcsim.util.Driver.doProcess(Driver.java:261)
        at org.lcsim.util.Driver.processChildren(Driver.java:271)
        at org.lcsim.util.Driver.process(Driver.java:187)
        at org.lcsim.util.DriverAdapter.recordSupplied(DriverAdapter.java:74)
        at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:832)
        at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:668)
        at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
        at org.lcsim.util.loop.LCSimLoop.loop(LCSimLoop.java:154)
        at org.lcsim.job.JobControlManager.run(JobControlManager.java:962)
        at org.hps.job.JobManager.main(JobManager.java:35)
2018-02-10 15:00:51 [SEVERE] org.lcsim.job.JobControlManager run :: A fatal error occurred when running the job.
java.lang.RuntimeException: java.lang.NullPointerException
        at org.lcsim.util.loop.LCSimLoop.handleClientError(LCSimLoop.java:194)
        at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:834)
        at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:668)
        at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
        at org.lcsim.util.loop.LCSimLoop.loop(LCSimLoop.java:154)
        at org.lcsim.job.JobControlManager.run(JobControlManager.java:962)
        at org.hps.job.JobManager.main(JobManager.java:35)
Caused by: java.lang.NullPointerException
        at org.lcsim.event.base.BaseHit.findDetectorElement(BaseHit.java:219)
        at org.lcsim.event.base.BaseHit.calculatePosition(BaseHit.java:189)
        at org.lcsim.event.base.BaseHit.getPosition(BaseHit.java:166)
        at org.lcsim.lcio.SIOCalorimeterHit.write(SIOCalorimeterHit.java:74)
        at org.lcsim.lcio.SIOCalorimeterHitBlockHandler.writeCollectionElement(SIOCalorimeterHitBlockHandler.java:40)
        at org.lcsim.lcio.AbstractBlockHandler.writeBlock(AbstractBlockHandler.java:55)
        at org.lcsim.lcio.LCIOWriter.writeData(LCIOWriter.java:220)
        at org.lcsim.lcio.LCIOWriter.write(LCIOWriter.java:254)
        at org.hps.readout.ReadoutDataManager.process(ReadoutDataManager.java:210)
        at org.lcsim.util.Driver.doProcess(Driver.java:261)
        at org.lcsim.util.Driver.processChildren(Driver.java:271)
        at org.lcsim.util.Driver.process(Driver.java:187)
        at org.lcsim.util.DriverAdapter.recordSupplied(DriverAdapter.java:74)
        at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:832)
        ... 5 more
```

I suspect that metadata is missing for these hits as well. The code causing this error is not included in the issue repository, since it causes an exception, but it can be inserted by adding the following method to `org.hps.readout.ecal.updated.GTPClusterReadoutDriver`:

```
    @Override
    protected Collection<LcsimSingleEventCollectionData<?>> getOnTriggerData(double triggerTime) {
        List<LcsimSingleEventCollectionData<?>> collectionsList = new ArrayList<LcsimSingleEventCollectionData<?>>(2);
        
        
        LcsimCollection<Cluster> clusterCollectionParams = new LcsimCollection<Cluster>("DebugClusters", this, Cluster.class, getTimeDisplacement());
        clusterCollectionParams.setFlags(1 << LCIOConstants.CLBIT_HITS);
        
        
        LcsimCollection<CalorimeterHit> clusterHitsCollectionParams = new LcsimCollection<CalorimeterHit>("DebugClusterHits", this, CalorimeterHit.class, 0.0);
        int clusterHitFlags = 0;
        clusterHitsCollectionParams.setFlags(clusterHitFlags);
        
        double startTime = triggerTime - 138;
        double endTime = triggerTime + 258;
        
        Collection<Cluster> clusters = ReadoutDataManager.getData(startTime, endTime, outputCollectionName, Cluster.class);
        List<CalorimeterHit> clusterHits = new ArrayList<CalorimeterHit>();
        for(Cluster cluster : clusters) {
            clusterHits.addAll(cluster.getCalorimeterHits());
        }
        
        LcsimSingleEventCollectionData<CalorimeterHit> clusterHitData = new LcsimSingleEventCollectionData<CalorimeterHit>(clusterHitsCollectionParams);
        clusterHitData.getData().addAll(clusterHits);
        collectionsList.add(clusterHitData);
        
        LcsimSingleEventCollectionData<Cluster> clusterData = new LcsimSingleEventCollectionData<Cluster>(clusterCollectionParams);
        clusterData.getData().addAll(clusters);
        collectionsList.add(clusterData);
        
        return collectionsList;
    }
```

No other alterations are necessary.

**Comment by mccaky** [comment]
Issues are now repaired. Hits were outputting incorrectly due to missing a proper "Readout name" parameter, and clusters did in fact just need their hits output. Error when outputting cluster hits resolved for unknown reasons while working on other issues.
