### ISSUE TITLE
Tracking test fails

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#307]
TruthResidualTest

```
java.awt.AWTError: Can't connect to X11 window server using 'localhost:11.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at hep.aida.ref.plotter.FontStyleParameter.<clinit>(FontStyleParameter.java:16)
	at hep.aida.ref.plotter.TextStyle.initializeBaseStyle(TextStyle.java:14)
	at hep.aida.ref.plotter.BaseStyle.<init>(BaseStyle.java:31)
	at hep.aida.ref.plotter.BrushStyle.<init>(BrushStyle.java:13)
	at hep.aida.ref.plotter.TextStyle.<init>(TextStyle.java:10)
	at hep.aida.ref.plotter.InfoStyle.initializeBaseStyle(InfoStyle.java:14)
	at hep.aida.ref.plotter.BaseStyle.<init>(BaseStyle.java:31)
	at hep.aida.ref.plotter.InfoStyle.<init>(InfoStyle.java:11)
	at hep.aida.ref.plotter.PlotterStyle.initializeBaseStyle(PlotterStyle.java:56)
	at hep.aida.ref.plotter.BaseStyle.<init>(BaseStyle.java:31)
	at hep.aida.ref.plotter.PlotterStyle.<init>(PlotterStyle.java:23)
	at hep.aida.ref.plotter.DummyPlotter.<init>(DummyPlotter.java:46)
	at hep.aida.ref.plotter.DummyPlotterFactory.create(DummyPlotterFactory.java:24)
	at hep.aida.ref.plotter.DummyPlotterFactory.create(DummyPlotterFactory.java:29)
	at org.hps.recon.tracking.gbl.TruthResiduals.makePlots(TruthResiduals.java:228)
	at org.hps.recon.tracking.gbl.TruthResiduals.processSim(TruthResiduals.java:69)
	at org.hps.recon.tracking.TruthResidualTest$TestResiduals.process(TruthResidualTest.java:96)
	at org.lcsim.util.Driver.doProcess(Driver.java:261)
	at org.lcsim.util.Driver.processChildren(Driver.java:271)
	at org.lcsim.util.Driver.process(Driver.java:187)
	at org.lcsim.util.DriverAdapter.recordSupplied(DriverAdapter.java:74)
	at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:832)
	at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:668)
	at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
	at org.lcsim.util.loop.LCSimLoop.loop(LCSimLoop.java:154)
```

Dumb AIDA init error.

**Comment by mdiamon** [comment]
This is that weird AIDA problem which you had fixed months ago.  How did it suddenly get un-fixed?  We didn't make any changes to this test recently...

**Comment by JeremyMcCormick** [comment]
Not sure why this broke all of a sudden but PR #308 should fix it permanently.
