### ISSUE TITLE
Make DatabaseConditionsManager constructor private. Update getInstance()

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-java#338]
See Issue336 and thread on SLACK: https://heavyphotonsearch.slack.com/archives/C449ZNYAV/p1541093083015100

DatabaseConditionsManager should have a private constructor, and all instances of: "new DatabaseConditionsManager()" should be replaced with "DatabaseConditionsManager.getInstance()".

This would improve reliability of the connections to the DB.

**Comment by mholtrop** [comment]
This is more than a needed enhancement. Since some code is currently not properly working as is.
`java -cp /data/HPS/hps-java/distribution/target/hps-distribution-4.1-SNAPSHOT-bin.jar  org.hps.detector.DetectorConverter -f lcdd -i detectors/HPS-PhysicsRun2016-Hodoscope-v3-2pt3-fieldmap/compact.xml  -o test.lcdd
Nov 14, 2018 5:38:43 PM org.lcsim.geometry.compact.converter.HPSTracker2014GeometryDefinition build
INFO: HPSTracker2014v1GeometryDefinition: Constructed 14 geometry objects
Nov 14, 2018 5:38:43 PM org.lcsim.geometry.compact.converter.HPSTracker2014GeometryDefinition build
INFO: HPSTracker2014v1GeometryDefinition: Constructed 12 module bundles
HPSTracker2014v1LCDDBuilder: Built 192 LCDD geometry objects
Exception in thread "main" java.lang.ClassCastException: Cannot cast org.lcsim.conditions.ConditionsManagerImplementation to org.hps.conditions.database.DatabaseConditionsManager
	at java.lang.Class.cast(Class.java:3369)
	at org.hps.conditions.database.DatabaseConditionsManager.getInstance(DatabaseConditionsManager.java:80)
	at org.lcsim.geometry.compact.converter.lcdd.HPSEcal4.addToLCDD(HPSEcal4.java:89)
	at org.lcsim.geometry.compact.converter.lcdd.LCDDDetector.writeSubdetectors(LCDDDetector.java:214)
	at org.lcsim.geometry.compact.converter.lcdd.LCDDDetector.writeLCDD(LCDDDetector.java:133)
	at org.lcsim.geometry.compact.converter.lcdd.Main.convert(Main.java:63)
	at org.hps.detector.DetectorConverter.run(DetectorConverter.java:117)
	at org.hps.detector.DetectorConverter.main(DetectorConverter.java:53)
`

**Comment by JeremyMcCormick** [comment]
This should be resolved by #412.
