### ISSUE TITLE
NullPointer in TupleMaker

### ISSUE THREAD

**Issue by brigidcrowe** [JeffersonLab/hps-java#424]
When running the TupleMaker on a recon file made with PhysicRun2016FullReconMC.lcsim (post iss422 merge), the following NullPointerException occurs.

Command:

```
java -jar /u/group/hps/hps_soft/git/hps-java_current/hps-java_2019Apr02_iss422isMerged/distribution/target/hps-distribution-4.3-SNAPSHOT-bin.jar /u/group/hps/hps_soft/git/hps-java_current/hps-java_2019Apr02_iss422isMerged/steering-files/src/main/resources/org/hps/steering/analysis/MakeTuplesFullTruthMC.lcsim -i /w/hallb-scifs17exp/general/hps/mc_production/PhysicsRun2016/test/iss422/recon_iss422.slcio -DoutputFile=tuple
```

tag: null
createdBy: jeremym
notes: nominal beam energy for physrun2016

```
java.lang.NullPointerException
    at org.hps.analysis.tuple.TupleMaker.detectorChanged(TupleMaker.java:189)
    at org.lcsim.util.Driver.detectorChanged(Driver.java:170)
    at org.lcsim.util.DriverAdapter.detectorChanged(DriverAdapter.java:86)
    at org.lcsim.util.DriverAdapter.recordSupplied(DriverAdapter.java:72)
    at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:832)
    at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:668)
    at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
    at org.lcsim.util.loop.LCSimLoop.loop(LCSimLoop.java:152)
    at org.lcsim.job.JobControlManager.run(JobControlManager.java:949)
    at org.hps.job.JobManager.main(JobManager.java:33)
```

The line appearing to cause the exception (TupleMaker.java:189): 
tupleWriter.println(StringUtils.join(tupleVariables, ":"));

There is no diff in the TupleMaker or TridentTupleMaker since it previously worked.

**Comment by JeremyMcCormick** [comment]
@byale-jlab 

I can't reproduce this.

I am using a clean copy of the master:

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.
```

I downloaded your input file and run locally with this command:

```
java -jar hps-distribution-bin.jar -r  /org/hps/steering/analysis/MakeTuplesFullTruthMC.lcsim -i recon_iss422.slcio -DoutputFile=tuple
```

The tuple output files are produced normally, and there's no crash.

I think you are not using a clean copy of the master and have some mix of different branches there which is causing issues.
