### ISSUE TITLE
Add MC conditions with no L0 and beam energy 4.55 GeV

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#486]
Extend the base conditions that are on 1000000 - 1000010 to 1000011 except for the `svt_daq_map` which should use the one from 2016 (same as 2015 I think?) with no L0.

**Comment by brigidcrowe** [comment]
When running the command:

java -jar ${hps-java} -r /org/hps/steering/readout/PhysicsRun2016TrigPairs1.lcsim -i /cache/mss/hallb/hps/production/2019Run/noTilt/slic/ap/4pt55/HPS-PhysicsRun2019-beta1-4pt5/200/ap_tc_HPS-PhysicsRun2019-beta1-4pt5_98.slcio -DoutputFile=fubar -d HPS-PhysicsRun2019-beta1-4pt5 -R 1000011

I get this error:

HPSTracker2014v1JavaBuilder: DONE build JAVA modules

2019-05-23 23:16:24 [INFO] org.lcsim.detector.converter.compact.HPSEcal3Converter makeSubdetectorDetectorElement :: creating detector element for subdetector Ecal

2019-05-23 23:16:24 [INFO] org.lcsim.detector.converter.compact.HPSEcal3Converter convert :: converting subdetector Ecal

2019-05-23 23:16:25 [INFO] org.hps.detector.svt.SvtDetectorSetup conditionsChanged :: activating default setup

2019-05-23 23:16:25 [SEVERE] org.lcsim.job.JobControlManager run :: A fatal error occurred when running the job.

java.lang.RuntimeException: Error creating new conditions record.

        at org.hps.conditions.database.ConditionsRecordConverter.getData(ConditionsRecordConverter.java:67)

        at org.hps.conditions.database.ConditionsRecordConverter.getData(ConditionsRecordConverter.java:20)

        at org.lcsim.conditions.CachedConditionsImplementation.getCachedData(CachedConditionsImplementation.java:20)

        at org.hps.conditions.database.DatabaseConditionsManager.getConditionsRecords(DatabaseConditionsManager.java:528)

        at org.hps.conditions.database.DatabaseConditionsManager.findConditionsRecords(DatabaseConditionsManager.java:400)

        at org.hps.conditions.database.AbstractConditionsObjectConverter.getData(AbstractConditionsObjectConverter.java:93)

        at org.lcsim.conditions.CachedConditionsImplementation.getCachedData(CachedConditionsImplementation.java:20)

        at org.hps.conditions.svt.SvtConditionsConverter.getData(SvtConditionsConverter.java:38)

        at org.hps.conditions.svt.SvtConditionsConverter.getData(SvtConditionsConverter.java:16)

        at org.lcsim.conditions.CachedConditionsImplementation.getCachedData(CachedConditionsImplementation.java:20)

        at org.hps.detector.svt.SvtDetectorSetup.conditionsChanged(SvtDetectorSetup.java:99)

        at org.lcsim.conditions.ConditionsManagerImplementation.fireConditionsChanged(ConditionsManagerImplementation.java:122)

        at org.lcsim.conditions.ConditionsManagerImplementation.setConditionsReader(ConditionsManagerImplementation.java:69)

        at org.lcsim.conditions.ConditionsManagerImplementation.setDetector(ConditionsManagerImplementation.java:53)

        at org.hps.conditions.database.DatabaseConditionsManager.setDetector(DatabaseConditionsManager.java:814)

        at org.lcsim.job.DefaultConditionsSetup.setup(DefaultConditionsSetup.java:45)

        at org.lcsim.job.JobControlManager.run(JobControlManager.java:936)

        at org.hps.job.JobManager.main(JobManager.java:33)

Caused by: java.sql.SQLException: Value '2MC DAQ map for 2019 without L0.0000-00-00 00:00:00

                                                                                            svt_daq_map1000011�

                                                                                                               svt_daq_mapjeremym2019-05-22 02:17:551000011' can not be represented as java.sql.Timestamp

        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)

        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)

        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)

        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)

        at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:1102)

        at com.mysql.jdbc.BufferRow.getTimestampFast(BufferRow.java:576)

        at com.mysql.jdbc.ResultSetImpl.getTimestampInternal(ResultSetImpl.java:6592)

        at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:6192)

        at com.mysql.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:5058)

        at org.hps.conditions.api.BaseConditionsObject.select(BaseConditionsObject.java:331)

        at org.hps.conditions.database.ConditionsRecordConverter.getData(ConditionsRecordConverter.java:59)

        ... 17 more

**Comment by byale-jlab** [comment]
I included the entire thing above, but the important parts seem to be:

java.lang.RuntimeException: Error creating new conditions record.
Caused by: java.sql.SQLException: Value '2MC DAQ map for 2019 without L0.0000-00-00 00:00:00

                                                                                            svt_daq_map1000011�

                                                                                                               svt_daq_mapjeremym2019-05-22 02:17:551000011' can not be represented as java.sql.Timestamp

        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)

**Comment by brigidcrowe** [comment]
I included the entire error message above, but the important part seems to be:

java.lang.RuntimeException: Error creating new conditions record.

Caused by: java.sql.SQLException: Value '2MC DAQ map for 2019 without L0.0000-00-00 00:00:00 svt_daq_map1000011� svt_daq_mapjeremym2019-05-22 02:17:551000011' can not be represented as java.sql.Timestamp at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)

**Comment by brigidcrowe** [comment]
We need a "beyond critical" label.
