### ISSUE TITLE
Collection error when running Eng Run 2015 MC recon

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#61]
When I run a simple LCIO output from SLIC using `/org/hps/steering/recon/EngineeringRun2015FullReconMC.lcsim` I get this error on the first event:

```
2017-05-08 13:54:43 [INFO] org.lcsim.job.EventMarkerDriver process :: Event 0 with sequence 0
java.lang.IllegalArgumentException: Unknown event component EcalClusters
        at hep.physics.event.BaseEvent.get(BaseEvent.java:48)
        at org.lcsim.event.base.BaseLCSimEvent.get(BaseLCSimEvent.java:238)
        at org.hps.recon.ecal.cluster.CopyClusterCollectionDriver.process(CopyClusterCollectionDriver.java:75)
        at org.lcsim.util.Driver.doProcess(Driver.java:261)
        at org.lcsim.util.Driver.processChildren(Driver.java:271)
        at org.lcsim.util.Driver.process(Driver.java:187)
        at org.lcsim.util.DriverAdapter.recordSupplied(DriverAdapter.java:74)
        at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:832)
        at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:668)
        at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
        at org.lcsim.util.loop.LCSimLoop.loop(LCSimLoop.java:152)
        at org.lcsim.job.JobControlManager.run(JobControlManager.java:962)
        at org.hps.job.JobManager.main(JobManager.java:35)
2017-05-08 13:54:43 [SEVERE] org.lcsim.job.JobControlManager run :: A fatal error occurred when running the job.
java.lang.RuntimeException: java.lang.IllegalArgumentException: Unknown event component EcalClusters
        at org.lcsim.util.loop.LCSimLoop.handleClientError(LCSimLoop.java:194)
        at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:834)
        at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:668)
        at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
        at org.lcsim.util.loop.LCSimLoop.loop(LCSimLoop.java:152)
        at org.lcsim.job.JobControlManager.run(JobControlManager.java:962)
        at org.hps.job.JobManager.main(JobManager.java:35)
Caused by: java.lang.IllegalArgumentException: Unknown event component EcalClusters
        at hep.physics.event.BaseEvent.get(BaseEvent.java:48)
        at org.lcsim.event.base.BaseLCSimEvent.get(BaseLCSimEvent.java:238)
        at org.hps.recon.ecal.cluster.CopyClusterCollectionDriver.process(CopyClusterCollectionDriver.java:75)
        at org.lcsim.util.Driver.doProcess(Driver.java:261)
        at org.lcsim.util.Driver.processChildren(Driver.java:271)
        at org.lcsim.util.Driver.process(Driver.java:187)
        at org.lcsim.util.DriverAdapter.recordSupplied(DriverAdapter.java:74)
        at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:832)
        ... 5 more
```

**Comment by mccaky** [comment]
Hello Jeremy,

Looking at the file, it is set up to run on readout data, which may be why
it gets confused when fed SLIC data. Have you run readout (the trigger
simulation) on your data yet?

Kyle

**Comment by JeremyMcCormick** [comment]
Okay, I am just trying to setup some programming facilities for job chaining, so I am attempting to get a minimal sim -> readout ->recon chain going for testing.  Any suggestions on what types of events I can use for this?  I was just using mollers directly from EGS but I doubt this is going to trigger in the readout.

**Comment by brigidcrowe** [comment]
Yeah, you have to run generated events through SLIC before readout. Particles that only exist at the target don't create too many triggers.



________________________________

**Comment by JeremyMcCormick** [comment]
Okay, that makes sense.  I was missing a step here I guess.

Though shouldn't the recon produce an empty EcalClusters collection even if it doesn't find any clusters in the event?  I suppose that is kind of an error condition because you're assuming that there were triggers and so clusters should be present.  But perhaps we should explicitly check for this instead of letting the recon continue until you get a cryptic error like this.
