### ISSUE TITLE
Kalman Filter: Remove hardcoded paths and remove default plotting

### ISSUE THREAD

**Issue by pbutti** [JeffersonLab/hps-java#659]
Remove hardcoded paths and disable plotting by default in KF pattern reco

**Comment by pbutti** [comment]
Also: remove printouts. 
Adding @robertprestonjohnson to keep him updated on the changes I'll be making to the package.

**Comment by pbutti** [comment]
Fixed issues with NaN covariant matrix in KalTracks with failed RK integration. 
Changed top/bottom check on Kalman Tracks (use of tanLambda instead of location of first hit)

**Comment by pbutti** [comment]
Changes to the Kalman Package and Particle Reconstruction Driver
- Removed verbose logging in Kalman Pattern Recognition
- Removed hardcoded path => configurable
- Removed default dump of plots => configurable. 
- Changed top/bottom check on tracks (from first hit location to tanLambda check) so it works on both Helix+GBL and Kalman Tracks
- Removed KalmanFullTracks with NaN cov matrix from track collection when RK extrapolation fails. 

- Compiles and runs on 1000evts and works in generating V0 collection

Test: org.hps.test.it.PhysRun2019ReconTest Fails with:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 21.495 sec <<< FAILURE! - in org.hps.test.it.PhysRun2019ReconTest
testIt(org.hps.test.it.PhysRun2019ReconTest)  Time elapsed: 21.432 sec  <<< ERROR!
java.lang.NullPointerException
	at org.hps.record.scalers.ScalerData.getScalerData(ScalerData.java:260)
	at org.hps.record.scalers.ScalersEvioProcessor.process(ScalersEvioProcessor.java:70)
	at org.hps.evio.LCSimEngRunEventBuilder.writeScalerData(LCSimEngRunEventBuilder.java:253)
	at org.hps.evio.LCSimEngRunEventBuilder.makeLCSimEvent(LCSimEngRunEventBuilder.java:198)
	at org.hps.evio.LCSimPhys2019EventBuilder.makeLCSimEvent(LCSimPhys2019EventBuilder.java:56)
	at org.hps.evio.EvioToLcio.run(EvioToLcio.java:608)
	at org.hps.evio.EvioToLcio.main(EvioToLcio.java:92)
	at org.hps.test.it.PhysRun2019ReconTest.testIt(PhysRun2019ReconTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

**Comment by pbutti** [comment]
Rebased to iss204e to get commit b65e7daf4

**Comment by pbutti** [comment]
- Imported last iss204e commits with latest Robert's fixes
- Test error also appears in master and not related to this branch
- Added Driver for MC truth information for Kalman Tracks (still some work ongoing)
- Added custom tracks for storing KF tracks in trackCollection
- Extrapolation to Calorimeter, TrackData [no isolation yet], V0s formation. 

Doesn't disrupt nominal reco.
