### ISSUE TITLE
Error for producing wab-beam sample at readout level

### ISSUE THREAD

**Issue by tongtongcao** [JeffersonLab/hps-java#686]
There is an error for producing wab-beam at readout level.

```
java.lang.OutOfMemoryError: Java heap space
Exception in thread “main” java.lang.OutOfMemoryError: Java heap space
        at java.lang.Throwable.getStackTraceElement(Native Method)
        at java.lang.Throwable.getOurStackTrace(Throwable.java:828)
        at java.lang.Throwable.printStackTrace(Throwable.java:657)
        at java.lang.Throwable.printStackTrace(Throwable.java:644)
        at java.lang.Throwable.printStackTrace(Throwable.java:635)
        at org.lcsim.util.loop.LCSimLoop.handleSourceError(LCSimLoop.java:199)
        at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:655)
        at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
        at org.lcsim.util.loop.LCSimLoop.loop(LCSimLoop.java:152)
        at org.lcsim.job.JobControlManager.run(JobControlManager.java:949)
        at org.hps.job.JobManager.main(JobManager.java:33)
1931.86user 109.91system 34:39.62elapsed 98%CPU (0avgtext+0avgdata 8237048maxresident)k
1115816inputs+518952outputs (0major+153913831minor)pagefaults 0swaps
```

There is no problem for producing pure wab sample. But after mixing beam bunches as background, the error happened. I did test by increasing `-Xmx500m` to `-Xmx8000m`. Still has such errors.

If anybody would like to do test, here is a test file for wab-beam mixture from slic level: 

```
/w/hallb-scifs17exp/general/hps/caot/mcData/2019/test/slic/beam/4pt55/merged.slcio
```

Here is an example for readout command: 

```
/usr/bin/java -XX:+UseSerialGC -Xmx8000m -jar /u/group/hps/hps_soft/hps-java/hps-distribution-4.5-SNAPSHOT-bin.jar -r /org/hps/steering/readout/PhysicsRun2019TrigPulse.lcsim -i merged.slcio -DoutputFile=out_readout -d HPS-PhysicsRun2019-v2-4pt5 -R 10666
```

hps-java branch: iss677. The branch has been merged into master.

Some tests have been done. 
1) A simple and clean steering file, set -Xmx500m: crashed.
2) A steering file with fully readout chain, set -Xmx8000m: crashed.
3) The same steering file as (1), set -Xmx8000m: worked
See plots at https://confluence.slac.stanford.edu/display/hpsg/2020.04.01+--+Software+Meeting?preview=/275712753/275712758/Issue%20for%20Memory%20Usage.pdf

**Comment by tongtongcao** [comment]
Thank all for supports. We solved the issue. The issue is not caused by memory leak. Instead, Jeremy and I found that there was issue for input data: there are too many MC particles in slic collections.
Go back to check egs5 level and slic level. There is issue in command for sampling which builds beam bunches for test: ${stdhep_dir}/random_sample_usingInputEventsInOrder -t”$poisson_mu_correction” -n250 rot_beam.stdhep sampled_beam -s 15${num}
In the command, -n250 should be -n25000, otherwise, 100 times electron events are included in each beam bunch. It causes too many MC particles in slic collections. Further, it causes that buffers in readout load too much data so that memory usage is even over 8G!!!
A stupid mistake causes big confusion. Have no idea why it was not noticed earlier.
Good news is that we do not struggle with noisy memory leak issue.
