### ISSUE TITLE
HodoscopeDataConverterTest crashes yet doesn't fail

### ISSUE THREAD

**Issue by cbravo135** [JeffersonLab/hps-java#770]
This can be reproduced by issuing `mvn -Dit.test=HodoscopeReadoutTest verify` from the integration-tests directory.
Seems like this test isn't actually doing anything except taking time during a `mvn clean install`, which is about an extra 2 minutes.

**Comment by JeremyMcCormick** [comment]
What's the error message?

**Comment by rafopar** [comment]
I can not reproduce this.
It passes tests for me

**Comment by cbravo135** [comment]
```
java.lang.NullPointerException
	at org.hps.readout.hodoscope.HodoscopeDigitizationReadoutDriver.getDAQPedestalConditions(HodoscopeDigitizationReadoutDriver.java:155)
	at org.hps.readout.DigitizationReadoutDriver.readHits(DigitizationReadoutDriver.java:472)
	at org.hps.readout.DigitizationReadoutDriver.process(DigitizationReadoutDriver.java:449)
	at org.lcsim.util.Driver.doProcess(Driver.java:261)
	at org.lcsim.util.Driver.processChildren(Driver.java:271)
	at org.lcsim.util.Driver.process(Driver.java:187)
	at org.lcsim.util.DriverAdapter.recordSupplied(DriverAdapter.java:74)
	at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:832)
	at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:668)
	at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
	at org.lcsim.util.loop.LCSimLoop.loop(LCSimLoop.java:152)
	at org.lcsim.job.JobControlManager.run(JobControlManager.java:949)
	at org.hps.test.it.HodoscopeReadoutTest.testHodoscopeReadout(HodoscopeReadoutTest.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
org.lcsim.job:SEVERE A fatal error occurred when running the job.
java.lang.RuntimeException: java.lang.NullPointerException
	at org.lcsim.util.loop.LCSimLoop.handleClientError(LCSimLoop.java:194)
	at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:834)
	at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:668)
	at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
	at org.lcsim.util.loop.LCSimLoop.loop(LCSimLoop.java:152)
	at org.lcsim.job.JobControlManager.run(JobControlManager.java:949)
	at org.hps.test.it.HodoscopeReadoutTest.testHodoscopeReadout(HodoscopeReadoutTest.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.NullPointerException
	at org.hps.readout.hodoscope.HodoscopeDigitizationReadoutDriver.getDAQPedestalConditions(HodoscopeDigitizationReadoutDriver.java:155)
	at org.hps.readout.DigitizationReadoutDriver.readHits(DigitizationReadoutDriver.java:472)
	at org.hps.readout.DigitizationReadoutDriver.process(DigitizationReadoutDriver.java:449)
	at org.lcsim.util.Driver.doProcess(Driver.java:261)
	at org.lcsim.util.Driver.processChildren(Driver.java:271)
	at org.lcsim.util.Driver.process(Driver.java:187)
	at org.lcsim.util.DriverAdapter.recordSupplied(DriverAdapter.java:74)
	at org.freehep.record.loop.DefaultRecordLoop.consumeRecord(DefaultRecordLoop.java:832)
	... 25 more

maxTimestamp = -1.0
minTimestamp = 9.99999999E8
Driver                                   0 0.00ms
   HodoscopeReadoutTest$HodoAnalDriver   0 0.00ms
      HodoscopeReadoutTest$HodoHitsDrive 0 0.00ms
      HodoscopeReadoutTest$EcalClustersG 0 0.00ms
      HodoscopeReadoutTest$EcalHitsDrive 0 0.00ms
      HodoscopeReadoutTest$HodoscopeRead 0 0.00ms
      HodoscopeReadoutTest$TrackerHitsEC 0 0.00ms
      HodoscopeReadoutTest$ReadoutTimest 0 0.00ms
      HodoscopeReadoutTest$MCParticleDri 0 0.00ms
      *self                              0 0.00ms
   HodoscopePlotsDriver                  0 0.00ms
   AidaSaveDriver                        0 0.00ms
   *self                                 0 0.00ms
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 129.457 sec - in org.hps.test.it.HodoscopeReadoutTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by cbravo135** [comment]
@rafopar You only need to run this one test. As is in the title of the issue, the test crashes but still passes, so what you are saying is consistent with the behavior reported in this issue.

**Comment by rafopar** [comment]
I can reproduce the issue now.
I am not sure what was wrong with my previous trial.
I did run only that test, i.e. used the command `mvn -Dit.test=HodoscopeReadoutTest verify`, but didn't see any exception

Ok will look at it now

**Comment by rafopar** [comment]
I just got a chance to look at this.
java.lang.NullPointerException
        at org.hps.readout.hodoscope.HodoscopeDigitizationReadoutDriver.getDAQPedestalConditions(HodoscopeDigitizationReadoutDriver.java:155)

The HodoscopeDigitizationReadoutDriver.java was developed by @mccaky  and @tongtongcao, 
Could one of you, look at this?

**Comment by JeremyMcCormick** [comment]
I just excluded the test on the lcsim42 branch for now

**Comment by tongtongcao** [comment]
I submitted a PR to fix the issue. Please review it.

**Comment by JeremyMcCormick** [comment]
This test is excluded from the build now from a merged PR.
